### ISSUE TITLE
General: Incorrect font-weight for Paragraph, OL, and UL content. It should be Light, not regular

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Danica-Carpentry#24]

**Comment by cyril-7175N** [comment]
Please provide a screenshot to replicate the issue.

**Comment by romatitan** [comment]
![image](https://cloud.githubusercontent.com/assets/12888048/16679672/ea7aad04-451b-11e6-9a98-06c697cbb18c.png)
![image](https://cloud.githubusercontent.com/assets/12888048/16679674/ecd78d06-451b-11e6-814c-bef7defa1967.png)
