### ISSUE TITLE
Admin - Login: Incorrect default login logo, tooltip and link

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Danica-Carpentry#7]
**If login logo field is blank, display the TitanDigital logo.**
**Tooltip (title) will be** "Titan Digital" **and link to** "http://www.titandigital.com.au/'

![image](https://cloud.githubusercontent.com/assets/12888048/16330091/6e5b5794-3a19-11e6-8133-d3c70eb5ecc7.png)
![image](https://cloud.githubusercontent.com/assets/12888048/16330095/704a0622-3a19-11e6-8467-03cda83f9744.png)

**Comment by romatitan** [comment]
Kindly check again.
It should be TITANDIGITAL logo, not titanweb.
![image](https://cloud.githubusercontent.com/assets/12888048/16682773/c7a57ed6-452e-11e6-895e-05ec1500db70.png)

**Comment by cyril-7175N** [comment]
Note: **New** Titan Digital logo is used as default login logo.
