### ISSUE TITLE
Projects: Style the Project Archives page properly

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Danica-Carpentry#72]
Note: Follow the layout style from Project page.
URL: http://danica-carpentry-imp.stage.titanweb.com.au/project/

![projects archives](https://cloud.githubusercontent.com/assets/12888048/16685577/94fb17f6-453e-11e6-9a7e-a3d855ed5b23.jpg)

**Comment by cyril-7175N** [comment]
Note: Used template is the same as the **Latest News** page.
