### ISSUE TITLE
General: Reduce the height of the page featured image.

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Danica-Carpentry#91]
Affected pages:
**FAQ
Testimonials
Gallery
Contact Us**

![image](https://cloud.githubusercontent.com/assets/12888048/16688247/c62542fa-454f-11e6-8bb9-3bca4e2156a6.png)
![image](https://cloud.githubusercontent.com/assets/12888048/16688254/cd989f0a-454f-11e6-8ead-62a592dd54de.png)

**Comment by cyril-7175N** [comment]
On basic inner pages , use smaller featured image as per design so that it will be consistent on all basic pages . On single pages, use full width featured image ( I talked to Roselie about this )
