### ISSUE TITLE
Header: Responsive error

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/Danica-Carpentry#99]
![image](https://cloud.githubusercontent.com/assets/12888048/16802296/ae63bec6-4932-11e6-9e26-e9d1c1402087.png)
![image](https://cloud.githubusercontent.com/assets/12888048/16802304/b87190aa-4932-11e6-9933-db78d6865f79.png)

**Comment by cyril-7175N** [comment]
( 992 - 1199px )  Instead, made it to 1 line so it will consistent with the desktop view.
